
name: ubunto build

on:
  workflow_dispatch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    env:
      TAGNAME: latest
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NuGet.exe for use with actions
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
      uses: NuGet/setup-nuget@v1.0.5
    - name: Adding Telerik NuGet
      run: dotnet nuget add source https://nuget.telerik.com/v3/index.json --username ${{ secrets.TELERIK_USER }} --password ${{ secrets.TELERIK_PASSWORD }} --store-password-in-clear-text --name telerik.com
    - name: Restore dependencies
      run: dotnet restore --packages ./packages
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    #- name: dotnet publish Cosmos Editor
    #  run: dotnet publish /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms/CDT.Cosmos.Cms.csproj -c Release -o /home/runner/work/app/editor
    #- name: List files
    #  run: ls app/editor
    #- name: dotnet publish Cosmos Publisher
    #  run: dotnet publish /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms.Website/CDT.Cosmos.Cms.Website.csproj -c Release -o /home/runner/work/app/publisher
    #- name: Upload Cosmos Editor artifact for deployment job
    #  uses: actions/upload-artifact@v2
    #  with:
    #      name: Cosmos Editor Artifact
    #      path: /home/runner/work/app/editor
        
    #- name: Upload Cosmos Publisher artifact for deployment job
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: Cosmos Publisher Artifact
    #    path: /home/runner/work/app/publisher
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
              username: ${{ secrets.DOCKERLOGIN }}
              password: ${{ secrets.DOCKERPASSWORD }}
    - name: Build Editor Docker image
      run: docker build . --file /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms/Dockerfile --tag toiyabe/cosmoseditor:${TAGNAME}
    - name: Docker push Editor image
      run:  docker push toiyabe/cosmoseditor:${TAGNAME}
    - name: Build Publisher Docker image
      run: docker build . --file /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms.Website/Dockerfile --tag toiyabe/cosmospublisher:${TAGNAME}
    - name: Docker push Publisher image
      run:  docker push toiyabe/cosmospublisher:${TAGNAME}
      

